image: node:8.12.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@7.0.5
  - npm install -g ionic cordova
  - npm install
  - ng build --prod --output-path public --base-href "/test/"
  artifacts:
    paths:
    - public
  only:
  - master
  - search-autocomplete
